x = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(x)}')
print(f'É número? {x.isnumeric()}')
print(f'Só tem espaços? {x.isspace()}')
print(f'É alfabético? {x.isalpha()}')
print(f'Alfanumérico? {x.isnumeric()}')
print(f'Letras maiúsculas? {x.isupper()}')
print(f"Letras minúsculas? {x.islower()}")
print(f'Está capitalizada? {x.istitle()}')
